"""Constants and metadata for narrative quality checks."""

from bookforge.core.issue import Severity

NARRATIVE_RULE_META = {
    "NARRATIVE_NAME_COLLISION": (Severity.SOFT, "First name '{first}' appears in current character '{current}' and prior character(s): {prior}. Rename or document intentional reuse."),
    "NARRATIVE_MISSING_BEATS": (Severity.SOFT, "Missing scene-breakdown beats; add intent-locked beats before continuing."),
    "NARRATIVE_UNIFORM_INTENT": (Severity.SOFT, "Uniform beat intent pattern in chapter; alternate action and consequence modes."),
    "NARRATIVE_NO_INTENT_MARKERS": (Severity.SOFT, "No explicit emotional, tactical, or institutional intent markers in scene beats."),
    "NARRATIVE_REPEATED_INTENSITY": (Severity.SOFT, "Large chapter shows repeated high-intensity processing; trim duplicate pressure loops."),
    "NARRATIVE_SYSTEMS_ONLY": (Severity.SOFT, "Scene progression reads as systems-only; every pressure phase needs a direct character-beat consequence."),
    "NARRATIVE_MISSING_STAKES": (Severity.SOFT, "Add a 'Human Stakes Carried' section in continuity-out.md for named characters carrying next-chapter pressure."),
    "NARRATIVE_NO_STAKE_ENTRIES": (Severity.SOFT, "Human Stakes Carried has no named character entries."),
    "NARRATIVE_NO_PRESSURE_WORDING": (Severity.SOFT, "{name} stake entry exists but has no pressure/cost wording."),
    "NARRATIVE_NO_SCENE_PRESSURE": (Severity.SOFT, "{name} has no direct scene pressure line in draft."),
    "NARRATIVE_ANTAGONIST_NO_TACTICS": (Severity.SOFT, "{name} is present but lacks distinct tactical markers; show tactical intent and chosen pressure method."),
    "NARRATIVE_ANTAGONIST_OVERLAP": (Severity.SOFT, "Active antagonists are framed with overlapping pressure posture; separate intent by tactic and emotional effect."),
    "NARRATIVE_ANTAGONIST_NO_COST": (Severity.SOFT, "At least one antagonist pressure scene is missing explicit emotional cost on named characters."),
    "NARRATIVE_WEAK_DECISIONS": (Severity.SOFT, "{count} decision transitions lack sensory/action grounding."),
    "NARRATIVE_NO_ROTATION": (Severity.SOFT, "Three consecutive chapters share one dominant scene intent; rotate intent class across chapters."),
}

ANTAGONIST_COST_TERMS = {
    "cost",
    "wound",
    "fear",
    "loss",
    "grief",
    "choice",
    "anger",
    "pain",
    "hurt",
    "blood",
    "death",
    "ruin",
    "burn",
    "pressure",
    "watch",
    "route",
    "count",
    "line",
    "ring",
    "horse",
    "claim",
    "statement",
    "shadow",
    "mark",
    "network",
    "threat",
}

INTENT_KEYWORDS = {
    "high-intensity action": [
        "fire",
        "shot",
        "raid",
        "ambush",
        "fight",
        "duel",
        "chase",
        "pursuit",
    ],
    "alliance/strategy": [
        "alliance",
        "council",
        "pact",
        "coordination",
        "plan",
        "strategy",
        "map",
        "signal",
    ],
    "emotional consequence": [
        "choice",
        "fear",
        "grief",
        "jealous",
        "trust",
        "loyal",
        "hesitate",
        "guilt",
    ],
    "institutional pressure": [
        "hearing",
        "witness",
        "statement",
        "court",
        "evidence",
        "law",
        "deposition",
        "paperwork",
    ],
    "recovery/repair": [
        "wound",
        "care",
        "stabil",
        "repair",
        "rest",
        "blood",
        "debrief",
        "aftercare",
    ],
}

SYSTEM_TERMS = {
    "pressure",
    "route",
    "routes",
    "watch",
    "mapping",
    "ledger",
    "testimony",
    "statement",
    "evidence",
    "coordination",
    "assign",
    "stabilize",
    "patrol",
}

SENSORY_ACTION_TERMS = {
    "dust",
    "horse",
    "leather",
    "iron",
    "rope",
    "timber",
    "mud",
    "water",
    "trail",
    "ridge",
    "boots",
    "shot",
    "fire",
    "blood",
    "fist",
    "door",
    "lamp",
    "rain",
    "sun",
    "wind",
    "saddle",
    "breath",
    "torch",
    "mud",
    "ridge",
    "jaw",
}

ACTION_VERBS = {
    "grip",
    "tied",
    "pulled",
    "loaded",
    "drove",
    "fired",
    "crossed",
    "pushed",
    "bent",
    "sealed",
    "bound",
    "tracked",
    "routed",
    "reached",
    "gripped",
    "struck",
    "leaned",
    "kicked",
    "dropped",
}

DECISION_TERMS = {
    "decide",
    "decides",
    "decided",
    "chooses",
    "choose",
    "resolve",
    "resolved",
}

STAKES_TERMS = {
    "risk",
    "cost",
    "burden",
    "choice",
    "stakes",
    "pressure",
    "wound",
    "fear",
    "loyal",
    "protect",
}

ROTATION_KEYS = tuple(INTENT_KEYWORDS.keys())

GENERIC_CHARACTER_HEADINGS = {
    "characters",
    "character profiles",
    "characters handoff state",
    "locations handoff state",
    "unresolved story pressures & setup",
    "major changes & chronology",
    "other source-locked roles",
    "from book 1",
    "from book 2",
    "from book 3",
}

EXPECTED_RECURRING_FIRST_NAMES = {"tex", "texas", "ghost"}
TITLE_WORDS = {"colonel", "old", "black", "jack"}
