"""BookForge Scanner package."""

from bookforge.core.scanner.outline import (
    SOURCE_NAMES,
    DEFAULT_TARGET_WORDS,
    TARGET_RE,
    BOOK_TARGET_CONTEXT_RE,
    NON_BOOK_TARGET_CONTEXT_RE,
    TITLE_FIELD_RE,
    HEADING_RE,
    CHAPTER_HEADING_RE,
    CHAPTER_LINE_RE,
    EPILOGUE_RE,
    SECTION_PATTERNS,
    TargetInfo,
    SourceScan,
    read_optional,
    source_path,
    normalize_target,
    first_target,
    first_book_target,
    resolve_target,
    detect_title,
    clean_inline,
    headings,
    section_present,
    chapter_matches,
    chapter_sections,
    has_summary_sections,
    scan_source,
    main_source_format,
)

from bookforge.core.scanner.style import (
    CATEGORIES,
    ING_OPENER_RE,
    ING_OPENER_EXCLUSIONS,
    DIALOGUE_TAG_RE,
    scan_file,
    check_gaps,
    main_banned_words,
    main_gaps,
)
